fishbanks/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("fishbanksapp.urls")),
    path("register/", v.register, name="register"),
    path('', include("django.contrib.auth.urls")),
]

fishbanksapp/urls.py
from django.urls import path
from . import views
from .views import get_game_time
from register.views import settings_view

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('myprofile/', views.myprofile, name='profile'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('purchase_ship/<int:ship_id>/', views.purchase_ship, name='purchase_ship'),
    path('config/', views.config, name='config'),
    path('api/get-time/', get_game_time, name='get-game-time'),
    path('invoice/<str:invoice_id>',views.invoice, name='invoice'),
    path('modify/<str:ship_id>', views.modify, name='modify'),
    path('invoices', views.invoice_list, name='invoice_list'),
    path('finances', views.user_finances, name='user_finances'),
    path('about', views.about, name='about'),
    path('inventory', views.user_inventory, name='inventory'),
    path('transactions', views.user_transactions, name='transactions'),
    path('group/create/', views.create_group, name='create_group'),
    path('group/<int:group_id>/', views.group_detail, name='group_detail'),
    path('group/<int:group_id>/add_member/', views.add_member, name='add_member'),
    path('groups', views.user_groups, name='groups'),
    path('group/<int:organization_id>/', views.group_detail, name='group_detail'),
    path('invitation/accept/<int:invitation_id>/', views.accept_invitation, name='accept_invitation'),
    path('invitation/decline/<int:invitation_id>/', views.decline_invitation, name='decline_invitation'),
    path('group/<int:group_id>/leave', views.leave_group, name='leave_group'),
    path('group/<int:group_id>/delete', views.delete_group, name='delete_group'),
    path('create_listing/<str:ship_id>', views.create_listing, name='create_listing'),
    path('buy_now/<int:auction_id>', views.buy_now, name='buy_now'),
    path('bid/<int:auction_id>/', views.place_bid, name='place_bid'),
    path('harbors/', views.harbors, name='harbors'),
    path('harbors/<int:harbor_id>', views.harbor_detail, name='harbor_detail'),
    path('market/', views.fish_market, name='fish_market'),
    path('trade/create/', views.create_trade_request, name='create_trade'),
    path('trade/', views.view_trades, name='view_trades'),
    path('trade/respond/<int:trade_id>/<str:response>/', views.respond_to_trade, name='respond_to_trade'),
    path('settings/', settings_view, name='settings'),
    path('api/get-species', views.export_fish_data_csv, name='get_species'),
    path('api/get-leaderboard', views.api_leaderboard, name='get_leaderboard'),
    path('net-leaderboard', views.net_worth_leaderboard, name='net_leaderboard'),
    path('api/get-users', views.get_user_data, name='get_user_data'),
    path('api/get-fish-values', views.get_fish_data, name='get_fish_data'),
]

fishbanksapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.serializers.json import DjangoJSONEncoder
from simple_history.models import HistoricalRecords
from django.utils.timezone import now
import time
from datetime import datetime

class Group(models.Model):
    history = HistoricalRecords()
    name = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_organizations', null=True)
    members = models.ManyToManyField(User, related_name='organizations')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Invitation(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('declined', 'Declined'),
    ]

    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_invitations')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_invitations')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='invitations')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Invitation from {self.sender} to {self.recipient} for {self.organization}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    balance = models.FloatField(default=1000.0)
    profile_picture = models.ImageField(upload_to='fishbanksapp/static/profile_pics/', blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    ships_list = models.JSONField(default=dict, encoder=DjangoJSONEncoder)
    history = HistoricalRecords()
    def __str__(self):
        return f"{self.user.username}'s Profile"
    
    # Automatically create a profile when a user is created
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()



class Transaction(models.Model):
    class TransactionType(models.TextChoices):
        PLAYER_TO_PLAYER = "P2P", "Player to Player"
        STORE_TO_PLAYER = "S2P", "Store to Player"
        PLAYER_TO_STORE = "P2S", "Player to Store"
        OTHER = "OTH", "Other"
    sender = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='transaction_sender')
    reciever = models.ForeignKey(User, related_name="received_transactions", on_delete=models.CASCADE, null=True, blank=True)
    date = models.CharField(default=None, max_length=100)

    transaction_type = models.CharField(
        max_length=3,
        choices=TransactionType.choices,
        default=TransactionType.PLAYER_TO_PLAYER
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=None, null=True)
    object_id = models.PositiveIntegerField(default=None, null=True)
    object = GenericForeignKey('content_type', 'object_id')
    def __str__(self):
        return f"{self.sender} sent {self.object} to {self.reciever} on {self.date}. This transaction is type {self.transaction_type}"
    
class InGameTime(models.Model):
    start_time = models.FloatField(default=0)
    game_start_time = models.FloatField(default=0)
    time_scale = models.FloatField(default=365.0)
    
        
    def resetTime(self):
        self.start_time = time.time()
        self.save()

    def getTime(self):
        current_time = time.time()
        return self.game_start_time + (current_time - self.start_time)*self.time_scale
    
    def formatTime(self, value):
        return datetime.fromtimestamp(int(value)).strftime('%Y-%m-%d %I:%M%p')
    
    def getFormattedTime(self):
        value = self.getTime()
        return self.formatTime(value)

class Harbor(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(blank=True, null=True, max_length=400)
    carrying_capacity = models.IntegerField(default=100000)
    storage_fee = models.FloatField(default=5000)
    def __str__(self):
        return self.name


class Ship(models.Model):
    history = HistoricalRecords()
    name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100, default='')
    fishing_capacity = models.IntegerField(default=0)
    cost = models.FloatField()
    fishing_rate = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    damage = models.FloatField(default=0)
    harbor = models.ForeignKey(Harbor, on_delete=models.SET_NULL, null=True, blank=True, related_name='ships_temp')  # New ForeignKey
    

    def __str__(self):
        return self.name
    
class ManufacturerShip(models.Model):
    name = models.CharField(max_length=100)
    fishing_capacity = models.IntegerField(default=0)
    fishing_rate = models.IntegerField()
    base_cost = models.FloatField()
    description = models.TextField(blank=True, null=True)
    stock = models.IntegerField(default=20)
    max_stock = models.IntegerField(default=30)

    def sellShip(self, customer):
        ship = Ship.objects.create(name=self.name, fishing_capacity=self.fishing_capacity, fishing_rate=self.fishing_rate, description=self.description, owner=customer, nickname=self.name, cost=self.base_cost)
        date = InGameTime.objects.first().getFormattedTime()
        self.stock -= 1
        self.save()
        Transaction.objects.create(sender=None, reciever=customer,
            transaction_type=Transaction.TransactionType.STORE_TO_PLAYER,
            content_type=ContentType.objects.get_for_model(Ship),
            object_id=ship.id,
            date=date
        )

    
class FishSpecies(models.Model):
    population = models.IntegerField(default=10000)
    value = models.FloatField(default=1.0)
    name = models.TextField(default=None)
    weight = models.FloatField(default=1.0)
    history = HistoricalRecords()
    harbor = models.ForeignKey(Harbor, on_delete=models.SET_NULL, null=True, blank=True, related_name='fish')  # New ForeignKey
    #growth parameters
    C = models.FloatField(default=100000)
    k = models.FloatField(default=0.01)

    def __str__(self):
        return f"Fish Stock: {self.population}, Value: ${self.value}"




class Invoice(models.Model):
    revenues = models.JSONField(default=dict, encoder=DjangoJSONEncoder)
    costs = models.JSONField(default=dict, encoder=DjangoJSONEncoder)
    date = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    def getProfit(self):
        total_r = 0
        total_c = 0
        for i in self.costs.values():
            total_c += i
        for i in self.revenues.values():
            total_r += i
        return total_r-total_c


class Gas(models.Model):
    price = models.FloatField(default=0.01)

    def __str__(self):
        return f"Gas price is {self.price} per fishing cycle per kg of fishing capacity on ship"
    
class AuctionListing(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('sold', 'Sold'),
        ('expired', 'Expired'),
    ]
    history = HistoricalRecords()
    end_time = models.DateTimeField(null=True, blank=True)
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE, related_name='listing_ship', null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    buy_now_price = models.FloatField(default=0)
    current_bid = models.FloatField(default=0)
    current_bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name='current_bidder', null=True)
    starting_bid = models.FloatField(default=0)
    details = models.TextField(null=True)
    listing_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_listing', null=True)

    def sellShip(self):
        """Finalize the sale when the auction ends."""
        if self.current_bidder:
            date = InGameTime.objects.first().getFormattedTime()
            self.current_bidder.profile.balance -= self.current_bid
            self.current_bidder.profile.save()
            self.listing_owner.profile.balance += self.current_bid
            self.listing_owner.save()
            
            Transaction.objects.create(
                sender=self.listing_owner,
                reciever=self.current_bidder,
                transaction_type=Transaction.TransactionType.PLAYER_TO_PLAYER,
                content_type=ContentType.objects.get_for_model(Ship),
                object_id=self.ship.id,
                date=date
            )
            
            self.ship.owner = self.current_bidder
            self.ship.save()
            self.status = 'sold'
        else:
            self.status = 'expired'       
        self.save()

    @classmethod
    def check_ended_auctions(cls):
        """Find auctions that have ended and process them."""
        ended_auctions = cls.objects.filter(end_time__lte=now(), status='pending')
        for auction in ended_auctions:
            auction.sellShip()
    
    def enter_bid(self, bid, customer):
        if (self.listing_owner != customer) and (self.end_time < now()):
            self.current_bidder = customer
            self.current_bid = bid

class TradeRequest(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    ]

fishbanksapp/forms.py
from django import forms
from .models import Ship, Group, AuctionListing, TradeRequest
from django.contrib.auth.models import User

class ShipForm(forms.ModelForm):
    class Meta:
        model = Ship
        fields = ['owner']  # Only allow editing the 'stock' attribute

class ShipUpdateForm(forms.ModelForm):
    class Meta:
        model = Ship
        fields = ['nickname', 'harbor']
        widgets = {
            'nickname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter new nickname'}),
            'harbor': forms.Select(attrs={'class': 'form-control'})
        }

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'description']

class InviteUserForm(forms.Form):
    recipient = forms.ModelChoiceField(queryset=User.objects.none(), label="Select User")
    

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users', User.objects.none())  # Get the users passed from the view
        super().__init__(*args, **kwargs)
        self.fields['recipient'].queryset = users  # Set the queryset for the dropdown


class AuctionListingForm(forms.ModelForm):
    class Meta:
        model = AuctionListing
        fields = ['buy_now_price', 'starting_bid', 'details', 'end_time']
        widgets = {
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class BidForm(forms.Form):
    bid_amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0.01)


class TradeRequestForm(forms.ModelForm):
    class Meta:
        model = TradeRequest
        fields = ['offered_ships', 'money_offered', 'requested_ships', 'money_requested']
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        recipient = kwargs.pop('recipient', None)
        super().__init__(*args, **kwargs)
        self.fields['offered_ships'].queryset = Ship.objects.filter(owner=user)
        if recipient:
            self.fields['requested_ships'].queryset = Ship.objects.filter(owner=recipient)
        else:
            self.fields['requested_ships'].queryset = Ship.objects.none()

fishbanksapp/templates/fishbanksapp/about.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 1em 0;
        }
        th, td {
          padding: 12px;
          border: 1px solid #ccc;
          text-align: left;
        }
        th {
          background-color: #f5f5f5;
        }
        ul {
          padding-left: 1.2em;
        }
      </style>
</head>
<body>
    <h1>Starter’s Guide</h1>

    <p>Welcome to <strong>OpenFishbanks</strong>, a multiplayer game where you manage a fishing company and try to maximize profit. This guide walks you through everything you need to know to get started.</p>

    <p>In OpenFishbanks, you play as the CEO of a fishing company.<br>
    Your goal: <strong>maximize your fishery's value</strong> by fishing, buying/selling boats, and managing resources wisely.<br>
    But be careful! The ocean has limited fish, and overfishing can hurt everyone — including you.</p>


    <h2>Creating an Account</h2>
    <p>To play OpenFishbanks, register as a new user by clicking on the login button, then <a href="{url 'login'}">“create new account.”</a> Fill out the necessary fields, and ensure you follow password rules, otherwise, your account will not be created.</p>

    <h2>In-game Time</h2>
    <p>The entire game revolves around an in-game time system, which is scaled at 365 times normal time. One day in real life equates to one year in-game, or one fishing season. The time is displayed at the top of the page.</p>

    <h2>Ships</h2>
    <p>Every player starts with a “starting ship” and $20,000. You can view your ships under “my fishery” and <a href="{url 'inventory'}">“inventory.”</a> To position your ship, click “modify ship” and select the harbor you want the ship to fish at. You can also set custom nicknames for each ship.</p>

    <h2>Harbors and Fish</h2>
    <p>There are 10 distinct harbors, each with its unique fish species. The values of each fish species vary based on the harbor fees and the size of the fish. Fish prices fluctuate based on the number of fish being sold. To track the value of the fish and see which harbors have which species, visit the <a href="{url 'fish_market'}">“fish market”</a> page.</p>

    <h2>Making Money</h2>
    <p>Every 30 minutes, your ships will return from a fishing trip, and an invoice will be generated. The invoice is a paycheck, displaying details on what ships were made, the amount of revenue, as well as the fees for fishing (including gas, workers, and harbor fees). Keeping track of your revenue and adapting your strategy on placing ships in different harbors will help you progress.</p>

    <h2>Auction</h2>
    <p>Users can buy and sell used ships on the auction. To create a listing, go to <a href="{url 'inventory'}">“inventory”</a> and auction the ship you want to sell. After filling out the necessary fields, a listing will be made that others can view on the <a href="{url 'shop'}">“shop”</a> page. To place a bid, enter a number in the bid field that is at least $500 more than the previous bid and click Enter Bid. The top bidder at the end of the auction period will receive the ship and will be charged the bid amount.</p>

    <h2>Trading</h2>
    <p>Users can also trade items and currency directly with one another, bypassing the auction system. To offer a trade to another user, visit the <a href="{url 'view_trades'}">“trading”</a> page, select the user you want to trade with, and click “initiate trade.” Users can accept or decline incoming trade offers on the “trading” page.</p>

    <h2>Groups</h2>
    <p>Groups or Organizations can be created on the “groups” page. You can join other groups if the group owner invites you. They are currently cosmetic and do not add any functionality beyond visibility on the leaderboard and your profile.</p>

    <h1>About OpenFishbanks</h1>
    <p>OpenFishbanks is an open-source and asycnhronous extension of MIT Sloan's <a href="https://mitsloan.mit.edu/teaching-resources-library/fishbanks-a-renewable-resource-management-simulation">Fishbanks</a> designed to simulate the dynamics of a fishing economy. It is built using Django and Python, with HTML, CSS, and Javascript for frontend. All code and assets are avaliable on the projects <a href="https://github.com/Quilliams85/OpenFishbanks">github repository</a>. Feel free to reach out to quinnryanwilliams@gmail.com with questions or concerns about OpenFishbanks.</p>

    <h2>Developers</h2>
    <h3>Quinn Williams</h3>
    <p>Quinn Williams is a senior at Concord Academy</p>
</body>

{% endblock %}

fishbanksapp/templates/fishbanksapp/config.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ship List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        input[type="number"] {
            width: 100px;
        }
    </style>
</head>
<body>
    <h2>Ship List</h1>
    <form method="post">
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Stock</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for ship, form in ships_and_forms %}
                <tr>
                    <td>{{ ship.name }}</td>
                    <td>
                        {{ form.stock }}
                        {% if form.stock.errors %}
                            <div class="error">{{ form.stock.errors }}</div>
                        {% endif %}
                    </td>
                    <td>
                        <button type="submit" name="ship_id" value="{{ ship.id }}">Update</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
    <h2> Salmon Chart</h2>
    <div>
        {{ chart_html|safe }}
    </div>
    <h2> Population Updates</h2>
    {%for record in history %}
    <li>
        <p>{{record.population}} on {{record.history_date}}</p>
    </li>
    {% endfor %}
</body>

{% endblock %}

fishbanksapp/templates/fishbanksapp/group_detail.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<body>
        <h1>{{ group.name }}</h1>
        <p>Created by: {{ group.owner.username }}</p>

        <h2>About</h2>
        <p>{{group.description}}</p>

        <h2>Members</h2>
        <ul class="list-group">
            {% for member in group.members.all %}
                <li class="list-group-item">{{ member.username }}</li>
            {% endfor %}
        </ul>

        {% if request.user == group.owner %}
            <h2>Invite User</h2>
            <form method="post" class="mb-3">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.recipient.label_tag }}
                    {{ form.recipient }}
                </div>
                <button type="submit" name="send_invite" class="btn btn-primary">Send Invite</button>
            </form>

            <h2>Pending Invitations</h2>
            <ul class="list-group">
                {% for invitation in pending_invitations %}
                    <li class="list-group-item">
                        Invitation to {{ invitation.recipient.username }} ({{ invitation.status }})
                    </li>
                {% endfor %}
            </ul>
            <form action="{% url 'delete_group' group.id%}" method="post">
                {% csrf_token %}
                <button type="submit" class="buy-button" style="background-color:red; width:auto;" onclick="return confirm('Are you sure you want to delete this organization? This change cannot be undone.')">
                    Delete Organization
                </button>
            </form>
        {% endif %}
</body>
{% endblock %}

fishbanksapp/templates/fishbanksapp/home.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <h1>Home Page</h1>
    <p>Welcome to OpenFishbanks!</p>
    {% if not user.is_authenticated %}
    <p> <strong>You are not logged in, sign in or create an account <a href="login">here</a></strong></p>
    {% endif %}

</body>

{% endblock %}

fishbanksapp/templates/fishbanksapp/invoice.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<head>
    <meta charset="utf-8" />
    <title>A simple, clean, and responsive HTML invoice template</title>

    <style>
        .invoice-box {
            max-width: 800px;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        .invoice-box table {
            width: 100%;
            line-height: inherit;
            text-align: left;
        }

        .invoice-box table td {
            padding: 5px;
            vertical-align: top;
        }

        .invoice-box table tr td:nth-child(2) {
            text-align: right;
        }

        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.top table td.title {
            font-size: 45px;
            line-height: 45px;
            color: #333;
        }

        .invoice-box table tr.information table td {
            padding-bottom: 40px;
        }

        .invoice-box table tr.heading td {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }

        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.item td {
            border-bottom: 1px solid #eee;
        }

        .invoice-box table tr.item.last td {
            border-bottom: none;
        }

        .invoice-box table tr.total td:nth-child(2) {
            border-top: 2px solid #eee;
            font-weight: bold;
        }

        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }

            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }

        /** RTL **/
        .invoice-box.rtl {
            direction: rtl;
            font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        }

        .invoice-box.rtl table {
            text-align: right;
        }

        .invoice-box.rtl table tr td:nth-child(2) {
            text-align: left;
        }
    </style>
</head>

<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <p>Open Fishbanks Invoice</p>
                            </td>

                            <td>
                                Invoice #: {{num}}<br />
                                Created:{{invoice.date}}<br />
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>


            <tr class="heading">
                <td>Revenue Item</td>

                <td>Value</td>
            </tr>
            {%for key, value in invoice.revenues.items%}
                <tr class="item">
                    <td>{{key}}</td>
                    <td>${{value}}</td>
                </tr>

            {%endfor%}
            <tr class="total">
                <td></td>

                <td>Total: $</td>
            </tr>
            <tr class="heading">
                <td>Cost Item</td>

                <td>Value</td>
            </tr>
            {%for key, value in invoice.costs.items%}
            <tr class="item">
                <td>{{key}}</td>
                <td>${{value}}</td>
            </tr>
            {%endfor%}
        </table>
        <div>
            <b>Total Profits: ${{profit}}</b>
        </div>
    </div>
</body>
{% endblock %}

fishbanksapp/templates/fishbanksapp/modify.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modify Ship</title>
</head>
<body>
    <h1>Modify {{ ship.nickname|default:ship.name }}</h1>
    <div class="card">
        <h3>Ship Details</h3>
        <p>Carrying Capacity: {{ship.fishing_capacity}}</p>
        <p>Fishing Rate: {{ship.fishing_rate}}</p>
        <p>Description: {{ship.description}}</p>
    </div>
    <p></p>

    <form method="post">
        {% csrf_token %}
        <div class="card">
            <div class="form-group">
                <label for="id_nickname">Ship Nickname:</label>
                <input type="text" name="nickname" id="id_nickname" value="{{ ship.nickname }}">
            </div>
            <p></p>
            <div class="form-group">
                <label for="id_harbor">Select Harbor:</label>
                <select name="harbor" id="harborSelect">
                    <option value="">None</option>
                    {% for harbor in form.fields.harbor.queryset %}
                        <option value="{{ harbor.id }}" {% if ship.harbor == harbor %}selected{% endif %}>
                            {{ harbor.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>    
        </div>
        <!-- Harbor Details Section -->
        <p></p>
        <div class="harbor-details" id="harborDetails">
            <div class="card">
                <h3>Selected Harbor</h3>
                {% if ship.harbor %}
                    <p><strong>Current Harbor:</strong> {{ ship.harbor.name }}</p>
                    <p><strong>Storage Fee:</strong> ${{ship.harbor.storage_fee}}</p>
                    <p><strong>Description:</strong> {{ship.harbor.description}}</p>

                {% else %}
                    <p>Select a harbor to view details.</p>
                {% endif %}
            </div>
        </div>
        <p></p>
        <button type="submit" class="buy-button">Save Changes</button>
    </form>    

    <script>
        document.getElementById("harborSelect").addEventListener("change", function() {
            const harbors = JSON.parse('{{ harbors_json|safe }}');  // Get harbor data
            const selectedHarborId = this.value;
            const harborDetailsDiv = document.getElementById("harborDetails");

            if (selectedHarborId in harbors) {
                const harbor = harbors[selectedHarborId];
                harborDetailsDiv.innerHTML = `
                    <p></p>
                    <div class='card'>
                        <h3>Selected Harbor</h3>
                        <p><strong>Current Harbor:</strong> ${harbor.name}</p>
                        <p><strong>Storage Fee:</strong> $${harbor.fee}</p>
                        <p><strong>Description:</strong> ${harbor.description}</p>
                    </div>
                `;
            } else {
                harborDetailsDiv.innerHTML = `
                    <p></p>
                    <div class='card'>
                            <h3>Selected Harbor</h3>
                            <p>Select a harbor to view details.</p>
                    </div>
                `;
            }
        });
    </script>

</body>
{% endblock %}

fishbanksapp/templates/fishbanksapp/successful_purchase.html
{% extends 'fishbanksapp/base.html' %}
{% block content %}
<p>Congratulations, you just purchased a  {{item}}!</p>
<a href="{% url 'shop' %}">Return to Shop</a>
{% endblock %}